apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
data:
  # Este script se ejecuta autom√°ticamente al iniciar MySQL por primera vez
  init-dbs.sql: |
    CREATE DATABASE IF NOT EXISTS userdb;
    CREATE DATABASE IF NOT EXISTS orderdb;
    CREATE DATABASE IF NOT EXISTS shippingdb;
    CREATE DATABASE IF NOT EXISTS paymentdb;
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
    FLUSH PRIVILEGES;
