grafana:
  adminPassword: "S3gura!2025"
  persistence:
    enabled: true

  # Habilita sidecar para cargar datasources externos
  sidecar:
    datasources:
      enabled: true

# Prometheus settings
prometheus:
  prometheusSpec:
    retention: "15d"
