apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-service-discovery
  namespace: {{ .Values.global.namespace }}
spec:
  # Aplica la polÃ­tica a los pods de Service Discovery
  podSelector:
    matchLabels:
      app: service-discovery
  policyTypes:
  - Ingress
  ingress:
  
  # Nota: El Service Discovery necesita recibir trÃ¡fico de casi todos
  # los demÃ¡s servicios para que puedan registrarse o consultarlo.
  
  # 1. Permite desde Cloud Config (a menudo necesita consultar el SD)
  - from:
    - podSelector:
        matchLabels:
          app: cloud-config
    ports:
    - protocol: TCP
      port: {{ index .Values "service-discovery" "service" "port" }} # ðŸ‘ˆ PUERTO CORREGIDO
      
  # 2. Permite desde Zipkin
  - from:
    - podSelector:
        matchLabels:
          app: zipkin
    ports:
    - protocol: TCP
      port: {{ index .Values "service-discovery" "service" "port" }}
      
  # 3. Permite desde Shipping Service
  - from:
    - podSelector:
        matchLabels:
          app: shipping-service
    ports:
    - protocol: TCP
      port: {{ index .Values "service-discovery" "service" "port" }}
      
  # 4. Permite desde Order Service
  - from:
    - podSelector:
        matchLabels:
          app: order-service
    ports:
    - protocol: TCP
      port: {{ index .Values "service-discovery" "service" "port" }}
      
  # 5. Permite desde Payment Service
  - from:
    - podSelector:
        matchLabels:
          app: payment-service
    ports:
    - protocol: TCP
      port: {{ index .Values "service-discovery" "service" "port" }}
      
  # 6. Permite desde Product Service
  - from:
    - podSelector:
        matchLabels:
          app: product-service
    ports:
    - protocol: TCP
      port: {{ index .Values "service-discovery" "service" "port" }}
      
  # 7. Permite desde User Service
  - from:
    - podSelector:
        matchLabels:
          app: user-service
    ports:
    - protocol: TCP
      port: {{ index .Values "service-discovery" "service" "port" }}
      
  # 8. Permite desde Favourite Service
  - from:
    - podSelector:
        matchLabels:
          app: favourite-service
    ports:
    - protocol: TCP
      port: {{ index .Values "service-discovery" "service" "port" }}
      
  # 9. Permite desde Proxy Client
  - from:
    - podSelector:
        matchLabels:
          app: proxy-client 
    ports:
    - protocol: TCP
      port: {{ index .Values "service-discovery" "service" "port" }}
      
  # 10. Permite desde API Gateway
  - from:
    - podSelector:
        matchLabels:
          app: api-gateway
    ports:
    - protocol: TCP
      port: {{ index .Values "service-discovery" "service" "port" }}