apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-payment-service
  namespace: {{ .Values.global.namespace }}
spec:
  # Aplica la pol√≠tica a los pods de Payment Service
  podSelector:
    matchLabels:
      app: payment-service
  policyTypes:
  - Ingress
  ingress:
  
  # 1. Regla: Permitir desde Order Service
  # La orden de compra inicia el pago
  - from:
    - podSelector:
        matchLabels:
          app: order-service
    ports:
    - protocol: TCP
      port: {{ index .Values "payment-service" "service" "port" }}
      
  # 2. Regla: Permitir desde Proxy Client (si el frontend necesita consultar estados de pago)
  - from:
    - podSelector:
        matchLabels:
          app: proxy-client
    ports:
    - protocol: TCP
      port: {{ index .Values "payment-service" "service" "port" }}