apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-favourite-service
  namespace: {{ .Values.global.namespace }}
spec:
  # Aplica la política a los pods de Favourite Service
  podSelector:
    matchLabels:
      app: favourite-service
  policyTypes:
  - Ingress
  ingress:
  
  # 1. Regla: Permitir desde Product Service
  # Necesita obtener detalles del producto para el favorito.
  - from:
    - podSelector:
        matchLabels:
          app: product-service
    ports:
    - protocol: TCP
      port: {{ index .Values "favourite-service" "service" "port" }}
      
  # 2. Regla: Permitir desde Proxy Client
  # La interfaz de usuario llama directamente para agregar/quitar favoritos.
  - from:
    - podSelector:
        matchLabels:
          app: proxy-client
    ports:
    - protocol: TCP
      port: {{ index .Values "favourite-service" "service" "port" }}
      
  # 3. Regla: Permitir desde User Service
  # Podría ser necesario para consultar la autenticación o detalles del usuario.
  - from:
    - podSelector:
        matchLabels:
          app: user-service
    ports:
    - protocol: TCP
      port: {{ index .Values "favourite-service" "service" "port" }}