{{- if (index .Values "favourite-service" "enabled") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: favourite-service
spec:
  replicas: {{ index .Values "favourite-service" "replicaCount" }}
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      initContainers:
          - name: wait-for-dependencies
            image: busybox
            command: ['sh', '-c', 'until nc -z cloud-config 9296 && nc -z service-discovery 8761; do echo waiting for dependencies; sleep 2; done;']
      containers:
      - name: favourite-service
        image: {{ index .Values "favourite-service" "image" "repository" }}:{{ index .Values "favourite-service" "image" "tag" }}
        ports:
          - containerPort: {{ index .Values "favourite-service" "service" "port" }}
        env:
          - name: MONGODB_URI
            value: mongodb://mongodb-0.mongodb:27017/favouritedb
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: SPRING_PROFILES_ACTIVE
                optional: false
          - name: SPRING_ZIPKIN_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: SPRING_ZIPKIN_BASE_URL
                optional: false
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: SPRING_CONFIG_IMPORT
                optional: false
          - name: EUREKA_CLIENT_REGION
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: EUREKA_CLIENT_REGION
                optional: false
          - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
                optional: false
          - name: EUREKA_CLIENT_SERVICEURL_MYZONE
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: EUREKA_CLIENT_SERVICEURL_MYZONE
                optional: false
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                optional: false
          - name: EUREKA_INSTANCE_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: favourite-service.EUREKA_INSTANCE_HOSTNAME
                optional: false
          - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
                optional: false
          - name: JAVA_TOOL_OPTIONS
            value: "-XX:MaxRAMPercentage=70.0"
        resources:
          requests:
            memory: {{ index .Values "favourite-service" "resources" "requests" "memory" }}
            cpu: {{ index .Values "favourite-service" "resources" "requests" "cpu" }}
          limits:
            memory: {{ index .Values "favourite-service" "resources" "limits" "memory" }}
            cpu: {{ index .Values "favourite-service" "resources" "limits" "cpu" }}
{{- end }}
