{{- if (index .Values "order-service" "enabled") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: order-service
spec:
  replicas: {{ index .Values "order-service" "replicaCount" }}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      initContainers:
          - name: wait-for-dependencies
            image: busybox
            command: ['sh', '-c', 'until nc -z service-discovery 8761 && nc -z cloud-config 9296 && nc -z mysql 3306; do echo waiting for dependencies; sleep 5; done;']
      containers:
      - name: order-service
        image: {{ index .Values "order-service" "image" "repository" }}:{{ index .Values "order-service" "image" "tag" }}
        ports:
          - containerPort: {{ index .Values "order-service" "service" "port" }}
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql:3306/orderdb?allowPublicKeyRetrieval=true&useSSL=false
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ecommerce-secrets
                key: mysql-root-password
                optional: false
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: update
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: SPRING_PROFILES_ACTIVE
                optional: false
          - name: SPRING_ZIPKIN_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: SPRING_ZIPKIN_BASE_URL
                optional: false
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: SPRING_CONFIG_IMPORT
                optional: false
          - name: EUREKA_CLIENT_REGION
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: EUREKA_CLIENT_REGION
                optional: false
          - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
                optional: false
          - name: EUREKA_CLIENT_SERVICEURL_MYZONE
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: EUREKA_CLIENT_SERVICEURL_MYZONE
                optional: false
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                optional: false
          - name: EUREKA_INSTANCE_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: order-service.EUREKA_INSTANCE_HOSTNAME
                optional: false
          - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
                optional: false
          - name: JAVA_TOOL_OPTIONS
            value: "-XX:MaxRAMPercentage=70.0"
        resources:
          requests:
            memory: {{ index .Values "order-service" "resources" "requests" "memory" }}
            cpu: {{ index .Values "order-service" "resources" "requests" "cpu" }}
          limits:
            memory: {{ index .Values "order-service" "resources" "limits" "memory" }}
            cpu: {{ index .Values "order-service" "resources" "limits" "cpu" }}
{{- end }}
