apiVersion: v1
kind: Service
metadata:
  name: cloud-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: cloud-config
spec:
  selector:
    app: cloud-config
    color: {{ .Values.blueGreen.activeColor }}
  ports: 
  - port: {{ index .Values "cloud-config" "service" "port" }}
    targetPort: {{ index .Values "cloud-config" "service" "port" }}
    protocol: TCP 
  type: {{ index .Values "cloud-config" "service" "type" }}
