{{- if (index .Values "zipkin" "enabled")}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-green
  namespace: {{ .Values.global.namespace }}
  labels:
    app: zipkin
spec:
  replicas: {{ .Values.zipkin.green.replicaCount}}
  selector:
    matchLabels:
      app: zipkin
      color: green
  template:
    metadata:
      labels:
        app: zipkin
        color: green
    spec:
      containers:
        - name: zipkin
          image: {{ .Values.zipkin.green.repository }}:{{ .Values.zipkin.green.tag }}
          ports:
            - containerPort: {{ .Values.zipkin.service.port }}
          resources:
            requests:
              memory: {{ .Values.zipkin.resources.requests.memory }}
              cpu: {{ .Values.zipkin.resources.requests.cpu }}
            limits:
              memory: {{ .Values.zipkin.resources.limits.memory }}
              cpu: {{ .Values.zipkin.resources.limits.cpu }}
{{- end }}